### PR TITLE
Updated for modern Django versions

### PR DESCRIPTION
**Pull request by joshowen**
This adds support for Python3, runs tests on travis-ci, and supports modern Django versions.

### CODE REVIEW

**Comment by joshowen** [comment]
hey @dimka665, any interest in getting this merged in and a new release out?  If not, would you mind adding me as a maintainer?

**Comment by joshowen** [comment]
Tests are passing here: https://travis-ci.org/joshowen/django-robots/builds/184026229

**Comment by joshowen** [comment]
@valeriansaliou I've included your changes in this PR, I'm hopeful that we can get a new release out that supports modern Django versions and Python3.

**Comment by valeriansaliou** [comment]
@joshowen thanks! Can you submit the PR directly to [https://github.com/valeriansaliou/django-robots](https://github.com/valeriansaliou/django-robots)? Not my repository there; cannot do anything.

**Comment by voronind** [comment]
Thank you very much

**Comment by joshowen** [comment]
@dimka665 would you mind making a pypi release?  Thanks!

**Pull request merged**
